spring:
    data:
        mongodb:
            host: ds163705.mlab.com
            port: 63705
            database: lab07
            username: ubuntu
            password: reverse  	
    redis:
        host: 192.168.56.102
        port: 6379
        #password:
